linters:
  # Reports when you use improper spacing around ! (the "bang") in !important and !default declarations.
  BangFormat:
    enabled: true
    severity: error

  # Prefer border: 0 over border: none.
  BorderZero:
    enabled: true
    severity: error

  # Prefer hexadecimal color codes over color keywords
  ColorKeyword:
    enabled: true
    severity: error

  # Prefer // comments over /* ... */
  Comment:
    enabled: true
    severity: error

  # Reports !debug statements
  DebugStatement:
    enabled: true
    severity: warning

  # Forces Extend, Mixins with no content, properties, mixins with content, nested rules
  DeclarationOrder:
    enabled: true
    severity: error

  # Prevent duplicate properties
  DuplicateProperty:
    enabled: true
    severity: error

  # Forces `else` on to new line
  ElsePlacement:
    enabled: true
    severity: error
    style: new_line

  # Separate rule, function, and mixin declarations with empty lines.
  EmptyLineBetweenBlocks:
    enabled: true
    severity: error
    ignore_single_line_blocks: false

  # Reports when you have an empty rule set.
  EmptyRule:
    enabled: true
    severity: error

  # Files should always have a final newline.
  FinalNewline:
    enabled: true
    severity: error
    present: true

  # Specifies whether you prefer shorthand or long-form hexadecimal colors by setting the style option to short or long, respectively.
  HexLength:
    enabled: true
    severity: error
    style: short

  # Checks if hexadecimal colors are written in lowercase.
  HexNotation:
    enabled: true
    severity: error
    style: lowercase

  # Ensure hexadecimal colors are valid
  HexValidation:
    enabled: true
    severity: error

  # Don't combine additional selectors with an ID selector.
  IdWithExtraneousSelector:
    enabled: true
    severity: error

  # The basenames of @imported SCSS partials should not begin with an underscore and should not include the filename extension
  ImportPath:
    enabled: true
    severity: error
    leading_underscore: false
    filename_extension: false

  # Use two spaces per indentation level.
  Indentation:
    enabled: true
    severity: error
    character: space
    width: 2

  # Dont write leading zeros for numeric values with a decimal point.
  LeadingZero:
    enabled: true
    severity: error
    style: exclude_zero

  # Reports when you define the same selector twice in a single sheet.
  MergeableSelector:
    enabled: true
    severity: warning
    force_nesting: true

  # Functions, mixins, and variables should be declared with all lowercase letters and hyphens instead of underscores.
  NameFormat:
    enabled: true
    severity: error
    convention: hyphenated_lowercase

  # Avoid nesting selectors too deeply.
  NestingDepth:
    enabled: true
    severity: error
    max_depth: 3

  # Always use placeholder selectors in @extend.
  PlaceholderInExtend:
    enabled: true
    severity: error

  # Sort properties in a strict order.
  # Using RECESS order (https://github.com/twitter/recess/blob/master/lib/lint/strict-property-order.js#L36)
  PropertySortOrder:
    enabled: true
    severity: error
    order:
      - position
      - top
      - right
      - bottom
      - left
      - z-index
      - display
      - float
      - width
      - height
      - max-width
      - max-height
      - min-width
      - min-height
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - margin-collapse
      - margin-top-collapse
      - margin-right-collapse
      - margin-bottom-collapse
      - margin-left-collapse
      - overflow
      - overflow-x
      - overflow-y
      - clip
      - clear
      - font
      - font-family
      - font-size
      - font-smoothing
      - osx-font-smoothing
      - font-style
      - font-weight
      - hyphens
      - src
      - line-height
      - letter-spacing
      - word-spacing
      - color
      - text-align
      - text-decoration
      - text-indent
      - text-overflow
      - text-rendering
      - text-size-adjust
      - text-shadow
      - text-transform
      - word-break
      - word-wrap
      - white-space
      - vertical-align
      - list-style
      - list-style-type
      - list-style-position
      - list-style-image
      - pointer-events
      - cursor
      - background
      - background-attachment
      - background-color
      - background-image
      - background-position
      - background-repeat
      - background-size
      - border
      - border-collapse
      - border-top
      - border-right
      - border-bottom
      - border-left
      - border-color
      - border-image
      - border-top-color
      - border-right-color
      - border-bottom-color
      - border-left-color
      - border-spacing
      - border-style
      - border-top-style
      - border-right-style
      - border-bottom-style
      - border-left-style
      - border-width
      - border-top-width
      - border-right-width
      - border-bottom-width
      - border-left-width
      - border-radius
      - border-top-right-radius
      - border-bottom-right-radius
      - border-bottom-left-radius
      - border-top-left-radius
      - border-radius-topright
      - border-radius-bottomright
      - border-radius-bottomleft
      - border-radius-topleft
      - content
      - quotes
      - outline
      - outline-offset
      - opacity
      - filter
      - visibility
      - size
      - zoom
      - transform
      - box-align
      - box-flex
      - box-orient
      - box-pack
      - box-shadow
      - box-sizing
      - table-layout
      - animation
      - animation-delay
      - animation-duration
      - animation-iteration-count
      - animation-name
      - animation-play-state
      - animation-timing-function
      - animation-fill-mode
      - transition
      - transition-delay
      - transition-duration
      - transition-property
      - transition-timing-function
      - background-clip
      - backface-visibility
      - resize
      - appearance
      - user-select
      - interpolation-mode
      - direction
      - marks
      - page
      - set-link-source
      - unicode-bidi
      - speak
    ignore_unspecified: false

  # Reports when you use an unknown CSS property
  PropertySpelling:
    enabled: true
    severity: error

  # Avoid qualifying elements in selectors
  QualifyingElement:
    enabled: true
    severity: error
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false

  # Don't write selectors with a depth of applicability greater than 3.
  SelectorDepth:
    enabled: true
    severity: error
    max_depth: 3

  # It is good practice to choose a convention for naming selectors.
  SelectorFormat:
    enabled: true
    severity: error
    convention: BEM

  # Prefer the shortest shorthand form possible for properties that support it.
  Shorthand:
    enabled: true
    severity: error

  # Properties within rule sets should each reside on their own line.
  SingleLinePerProperty:
    enabled: true
    severity: error
    allow_single_line_rule_sets: false

  # Split selectors onto separate lines after each comma.
  SingleLinePerSelector:
    enabled: true
    severity: error

  # Commas in lists should be followed by a space.
  SpaceAfterComma:
    enabled: true
    severity: error

  # Properties should be formatted with a single space separating the colon from the property's value.
  SpaceAfterPropertyColon:
    enabled: true
    severity: error
    style: one_space

  # Properties should be formatted with no space between the name and the colon.
  SpaceAfterPropertyName:
    enabled: true
    severity: error

  # Opening braces should be preceded by a single space.
  SpaceBeforeBrace:
    enabled: true
    severity: error
    allow_single_line_padding: false
    style: space

  # Parentheses should not be padded with spaces.
  SpaceBetweenParens:
    enabled: true
    severity: error
    spaces: 0

  # String literals should be written with single quotes unless using double quotes would save on escape characters.
  StringQuotes:
    enabled: true
    severity: error
    style: single_quotes

  # Property values; @extend, @include, and @import directives; and variable declarations should always end with a semicolon.
  TrailingSemicolon:
    enabled: true
    severity: error

  # Don't write trailing zeros for numeric values with a decimal point.
  TrailingZero:
    enabled: true
    severity: error

  # Numeric values should not contain unnecessary fractional portions.
  UnnecessaryMantissa:
    enabled: true
    severity: error

  # Do not use parent selector references (&) when they would otherwise be unnecessary.
  UnnecessaryParentReference:
    enabled: true
    severity: error

  # URLs should not contain protocols or domain names.
  UrlFormat:
    enabled: true
    severity: error

  # URLs should always be enclosed within quotes.
  UrlQuotes:
    enabled: true
    severity: error

  # Avoid vendor prefixes. That is, don't write them yourself.
  VendorPrefixes:
    enabled: true
    severity: error
    identifier_list: base

  # Omit length units on zero values.
  ZeroUnit:
    enabled: true
    severity: error
